# Generated by Django 4.2.14 on 2024-08-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("profile_pic", models.IntegerField(blank=True, null=True)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("occupation", models.CharField(max_length=50, null=True)),
                ("birth_date", models.DateField(null=True)),
                ("is_married", models.BooleanField(default=False)),
                ("email", models.EmailField(max_length=100, unique=True)),
            ],
        ),
    ]
