# Generated by Django 4.2.14 on 2024-09-03 18:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("matrimonal", "0003_profile_sects"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hobby",
            options={"verbose_name_plural": "Hobbies"},
        ),
        migrations.AlterModelOptions(
            name="sects",
            options={"verbose_name_plural": "Sects"},
        ),
    ]
