# Generated by Django 4.2.14 on 2024-09-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matrimonal", "0005_alter_profile_occupation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="hobby",
            field=models.ManyToManyField(
                blank=True, related_name="profiles", to="matrimonal.hobby"
            ),
        ),
    ]
